# Generated by Django 4.1.7 on 2023-03-21 00:53

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=30)),
                ('puesto', models.CharField(default='', max_length=30)),
                ('dependientes', models.IntegerField(default=0)),
            ],
            bases=(models.Model, general.models.Persona),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(default='', max_length=30)),
                ('anios_prof', models.IntegerField(default=0)),
            ],
            bases=(models.Model, general.models.Persona),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro_medico', models.CharField(default=0, max_length=30)),
                ('estudio', models.CharField(default='', max_length=30)),
            ],
            bases=(models.Model, general.models.Persona),
        ),
    ]
